import type { Listing } from "./types";

export const SEED_LISTINGS: Listing[] = [
  {
    id: "28hse-3996814",
    source: "28Hse",
    deal: "sale",
    url: "https://www.28hse.com/buy/apartment/property-3996814",
    title: "靚裝兩房大廳，海景",
    estate: "海灣樓",
    unit: "低層",
    sqft: 412,
    price: 3_800_000,
    beds: 2,
    baths: 1,
    agent: "範梁集團",
    image: "https://i1.28hse.com/2026/09/202609020952357185523_large.jpg",
    tags: ["2 房", "1 浴室", "單幢式大廈", "望海景"],
    posted: "近日",
    kind: "apartment",
    areaLabel: "南大嶼山",
  },
  {
    id: "28hse-3719244",
    source: "28Hse",
    deal: "sale",
    url: "https://www.28hse.com/buy/apartment/property-3719244",
    title: "獨家 地下 車可到門口 單邊罕有放盤",
    estate: "梅窩大地塘村",
    unit: "地下",
    sqft: 700,
    price: 3_500_000,
    beds: 3,
    baths: 1,
    agent: "四季物業",
    image: "https://i1.28hse.com/2026/01/202601261843448267733_large.jpg",
    tags: ["3 房", "村屋", "地下"],
    posted: "近日",
    kind: "village",
    areaLabel: "南大嶼山",
  },
  {
    id: "28hse-3944887",
    source: "28Hse",
    deal: "sale",
    url: "https://www.28hse.com/buy/apartment/property-3944887",
    title: "地下單位, 3房連寬敞大廳",
    estate: "梅窩大地塘村",
    unit: "地下",
    sqft: 700,
    price: 3_500_000,
    beds: 3,
    baths: 1,
    agent: "四季物業",
    image: "https://i1.28hse.com/2026/07/202607241526038388009_large.jpg",
    tags: ["3 房", "村屋"],
    posted: "近日",
    kind: "village",
    areaLabel: "南大嶼山",
  },
  {
    id: "28hse-3772067",
    source: "28Hse",
    deal: "sale",
    url: "https://www.28hse.com/buy/apartment/property-3772067",
    title: "梅窩村屋放售(G/F) 私人花園",
    estate: "橫塘",
    unit: "地下",
    sqft: 700,
    price: 4_050_000,
    beds: 3,
    baths: 2,
    agent: "四季物業 Tiffany",
    image: null,
    tags: ["3 房", "2 浴室", "村屋", "花園"],
    posted: "10 日前",
    kind: "village",
    areaLabel: "南大嶼山",
  },
  {
    id: "hs-53615-2",
    source: "HomeSolutions",
    deal: "sale",
    url: "https://homesolutions.hk/property-listing/53615-2/",
    title: "1/F MUI WO VILLAGE HOUSE",
    estate: "梅窩村屋",
    unit: "1樓",
    sqft: 430,
    price: 2_500_000,
    beds: 1,
    baths: 1,
    agent: "HomeSolutions",
    image: null,
    tags: ["村屋", "1 房"],
    posted: null,
    kind: "village",
    areaLabel: "梅窩",
  },
  {
    id: "hs-53154-2",
    source: "HomeSolutions",
    deal: "sale",
    url: "https://homesolutions.hk/property-listing/53154-2/",
    title: "1/F MUI WO VILLAGE HOUSE",
    estate: "梅窩村屋",
    unit: "1樓",
    sqft: 700,
    price: 4_550_000,
    beds: 2,
    baths: 1,
    agent: "HomeSolutions",
    image: null,
    tags: ["村屋", "2 房"],
    posted: null,
    kind: "village",
    areaLabel: "梅窩",
  },
  {
    id: "hs-53128-2",
    source: "HomeSolutions",
    deal: "sale",
    url: "https://homesolutions.hk/property-listing/53128-2/",
    title: "MUI WO FLAT + ROOFTOP",
    estate: "梅窩單位連天台",
    unit: "",
    sqft: 400,
    price: 2_980_000,
    beds: 3,
    baths: 1,
    agent: "HomeSolutions",
    image: null,
    tags: ["天台", "3 房"],
    posted: null,
    kind: "apartment",
    areaLabel: "梅窩",
  },
  {
    id: "28hse-3993346",
    source: "28Hse",
    deal: "sale",
    url: "https://www.28hse.com/buy/apartment/property-3993346",
    title: "梅窩近碼頭單位放售",
    estate: "卓濤軒",
    unit: "",
    sqft: 394,
    price: 4_950_000,
    beds: 2,
    baths: 1,
    agent: "四季物業",
    image: "https://i1.28hse.com/2026/08/202608301539583010449_large.jpg",
    tags: ["2 房", "近碼頭"],
    posted: "近日",
    kind: "apartment",
    areaLabel: "南大嶼山",
  },
  {
    id: "28hse-3996817",
    source: "28Hse",
    deal: "sale",
    url: "https://www.28hse.com/buy/apartment/property-3996817",
    title: "一房單位, 開揚海景",
    estate: "梅窩大廈",
    unit: "高層",
    sqft: 257,
    price: 2_300_000,
    beds: 1,
    baths: 1,
    agent: "範梁集團",
    image: "https://i1.28hse.com/2026/09/202609020956023247906_large.jpg",
    tags: ["1 房", "望海景"],
    posted: "近日",
    kind: "apartment",
    areaLabel: "南大嶼山",
  },
  {
    id: "hs-53874-2",
    source: "HomeSolutions",
    deal: "rent",
    url: "https://homesolutions.hk/property-listing/53874-2/",
    title: "1/F MUI WO VILLAGE HOUSE",
    estate: "梅窩村屋",
    unit: "1樓",
    sqft: 700,
    price: 11_500,
    beds: 3,
    baths: 1,
    agent: "HomeSolutions",
    image: null,
    tags: ["村屋", "3 房"],
    posted: null,
    kind: "village",
    areaLabel: "梅窩",
  },
  {
    id: "hs-53646-2",
    source: "HomeSolutions",
    deal: "rent",
    url: "https://homesolutions.hk/property-listing/53646-2/",
    title: "1/F MUI WO VILLAGE HOUSE",
    estate: "梅窩村屋",
    unit: "1樓",
    sqft: 700,
    price: 13_000,
    beds: 3,
    baths: 1,
    agent: "HomeSolutions",
    image: null,
    tags: ["村屋"],
    posted: null,
    kind: "village",
    areaLabel: "梅窩",
  },
  {
    id: "hs-53710-2",
    source: "HomeSolutions",
    deal: "rent",
    url: "https://homesolutions.hk/property-listing/53710-2/",
    title: "2/F MUI WO VILLAGE HOUSE + ROOFTOP",
    estate: "梅窩村屋連天台",
    unit: "2樓",
    sqft: 650,
    price: 13_000,
    beds: 2,
    baths: 1,
    agent: "HomeSolutions",
    image: null,
    tags: ["村屋", "天台"],
    posted: null,
    kind: "village",
    areaLabel: "梅窩",
  },
  {
    id: "hs-53681-2",
    source: "HomeSolutions",
    deal: "rent",
    url: "https://homesolutions.hk/property-listing/53681-2/",
    title: "1/F MUI WO VILLAGE HOUSE",
    estate: "梅窩村屋",
    unit: "1樓",
    sqft: 650,
    price: 11_800,
    beds: 2,
    baths: 1,
    agent: "HomeSolutions",
    image: null,
    tags: ["村屋"],
    posted: null,
    kind: "village",
    areaLabel: "梅窩",
  },
  {
    id: "hs-53832-2",
    source: "HomeSolutions",
    deal: "rent",
    url: "https://homesolutions.hk/property-listing/53832-2/",
    title: "RIVERWALK – MUI WO DUPLEX FLAT + TERRACE",
    estate: "銀河灣畔",
    unit: "複式連平台",
    sqft: 532,
    price: 16_800,
    beds: 1,
    baths: 1,
    agent: "HomeSolutions",
    image: null,
    tags: ["複式", "平台"],
    posted: null,
    kind: "apartment",
    areaLabel: "梅窩",
  },
  {
    id: "hs-53634-2",
    source: "HomeSolutions",
    deal: "rent",
    url: "https://homesolutions.hk/property-listing/53634-2/",
    title: "1/F MUI WO VILLAGE HOUSE",
    estate: "梅窩村屋",
    unit: "1樓",
    sqft: 430,
    price: 10_000,
    beds: 1,
    baths: 1,
    agent: "HomeSolutions",
    image: null,
    tags: ["村屋"],
    posted: null,
    kind: "village",
    areaLabel: "梅窩",
  },
  {
    id: "sp-ltt-rent-700",
    source: "Spacious",
    deal: "rent",
    url: "https://www.spacious.hk/zh-tw/%E9%A6%99%E6%B8%AF/n/137-%E6%A2%85%E7%AA%A9/b/68943--%E9%B9%BF%E5%9C%B0%E5%A1%98",
    title: "鹿地塘村屋 3房",
    estate: "鹿地塘",
    unit: "",
    sqft: 700,
    price: 11_500,
    beds: 3,
    baths: 1,
    agent: "千居",
    image: null,
    tags: ["村屋", "3 房"],
    posted: null,
    kind: "village",
    areaLabel: "梅窩",
  },
  {
    id: "sp-wt-rent-700",
    source: "Spacious",
    deal: "rent",
    url: "https://www.spacious.hk/zh-tw/%E9%A6%99%E6%B8%AF/n/137-%E6%A2%85%E7%AA%A9/b/66244--%E6%A9%AB%E5%A1%98",
    title: "橫塘村屋 3房",
    estate: "橫塘",
    unit: "",
    sqft: 700,
    price: 12_500,
    beds: 3,
    baths: 1,
    agent: "千居",
    image: null,
    tags: ["村屋", "3 房"],
    posted: null,
    kind: "village",
    areaLabel: "梅窩",
  },
];
